Project/Project/Models/Actor.cs
using System.ComponentModel.DataAnnotations;

namespace Project.Models
{
    public class Actor
    {
        [Key]
        public int Id { get; set; }


        [Display(Name = "")]
        [Required(ErrorMessage = "Hình ảnh bắt buộc")]
        public string Picture { get; set; }

        [Display(Name = "Tên")]
        [Required(ErrorMessage = "Họ tên bắt buộc")]
        [StringLength(50,MinimumLength = 2, ErrorMessage ="Họ tên ít nhất 2 chữ")]
        public string FullName { get; set; }

        [Display(Name = "Giới thiệu")]
        [Required(ErrorMessage = "Giới thiệu bắt buộc")]
        public string Description { get; set; }
        //Relationship
        public List<Actor_Movie> Actors_Movies { get; set; }
}
}

Project/Project/Models/Actor_Movie.cs
namespace Project.Models
{
    public class Actor_Movie
    {
        public int MovieId { get; set; }
        public Movie Movie { get; set; }
        public int ActorId { get; set; }
        public Actor Actor { get; set; }
    }
}

Project/Project/Models/Cinema.cs
using System.ComponentModel.DataAnnotations;

namespace Project.Models
{
    public class Cinema
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "")]
        public string Logo { get; set; }
        [Display(Name = "Tên")]
        public string Name { get; set; }
        [Display(Name = "Giới thiệu")]
        public string Description { get; set; }
        //Relationship
        public List<Movie> Movies { get; set; }
    }
}

Project/Project/Models/ErrorViewModel.cs
namespace Project.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Project/Project/Models/Movie.cs
using Project.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Project.Models
{
    public class Movie
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
       
        public string Description { get; set; }
        public Double Price { get; set; }
        public string ImageURl { get; set; }
        public DateTime StartDay { get; set; }
        public DateTime EndDay { get; set; }
        public MovieCategory MovieCategory { get; set; }
        //Relationship
        public List<Actor_Movie> Actors_Movies { get; set; }

        //Cinema
        public int CinemaId { get; set; }
        [ForeignKey("CinemaId")]
        public Cinema Cinema { get; set; }

        //Producer
        public int ProducerId { get; set; }
        [ForeignKey("ProducerId")]
        public Producer Producer { get; set; }

    }
}

Project/Project/Models/Producer.cs
using System.ComponentModel.DataAnnotations;

namespace Project.Models
{
    public class Producer
    {
        [Key]
        public int Id { get; set; }
        [Display(Name ="Tên")]
        public string FullName { get; set; }
        [Display(Name = "")]
        public string Picture { get; set; }
        [Display(Name = "Giới thiệu")]
        public string Description { get; set; }
        //Relationship
        public List<Movie> Movies { get; set; }
    }
}

Project/Project/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using Project.Data;
using Project.Data.Services;
using Project.Models;

namespace Project.Controllers
{
    public class ActorsController : Controller
    {
        public readonly IActorsService _service;

        public ActorsController(IActorsService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }
        // get : Create
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        
        public async Task<IActionResult> Create([Bind("FullName,Picture,Description")]Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            
            return RedirectToAction(nameof(Index));
        }

        // get : Detail/1
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }
        // get : Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }
        [HttpPost]

        public async Task<IActionResult> Edit(int id, [Bind("Id, FullName,Picture,Description")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id, actor);

            return RedirectToAction(nameof(Index));
        }

        // get : Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            return View(actorDetails);
        }
        [HttpPost, ActionName("Delete")]

        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");
            await _service.DeleteAsync(id);


            return RedirectToAction(nameof(Index));
        }
    }
}

Project/Project/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.Data;

namespace Project.Controllers
{
    public class CinemasController : Controller
    {
        public readonly AppDbContext _context;

        public CinemasController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allCinemas = await _context.Cinemas.ToListAsync();
            return View(allCinemas);
        }
    }
}

Project/Project/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.Data;

namespace Project.Controllers
{
    public class MoviesController : Controller
    {
        public readonly AppDbContext _context;

        public MoviesController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allMovies = await _context.Movies.Include(n => n.Cinema).OrderBy(n => n.Name).ToListAsync();
            return View(allMovies);
        }
    }
}

Project/Project/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.Data;

namespace Project.Controllers
{
    public class ProducersController : Controller
    {
        public readonly AppDbContext _context;

        public ProducersController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var allProducer = await _context.Producers.ToListAsync();
            return View(allProducer);
        }
    }
}

Project/Project/Views/Cinemas/Index.cshtml
@model IEnumerable<Cinema>

@{
    ViewData["Title"] = "Danh sách rạp chiếu phim";
}

<div class="row">
    <div class="col-md-8 offset-md-2">

        <table class="table">
            <thead>
                <tr class="text-center">
                    <th class="col-md-2">@Html.DisplayNameFor(model => model.Logo)</th>
                    <th class="col-md-2">@Html.DisplayNameFor(model => model.Name)</th>
                    <th class="col-md-5">@Html.DisplayNameFor(model => model.Description)</th>
                    <th class="col-md-3">-</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td class="align-middle col-md-2">
                            <img class="rounded-circle" src="@item.Logo" alt="@item.Name" style="max-width:150px" />
                        </td>
                        <td class="align-middle col-md-2">
                            @Html.DisplayFor(modelItem => item.Name);
                        </td>
                        <td class="align-middle col-md-5">
                            @Html.DisplayFor(modelItem => item.Description);
                        </td>
                        <td class="align-middle col-md-3">
                            <a class="btn btn-outline-primary"><i class="bi bi-pencil-square"></i></a> |
                            <a class="btn btn-outline-info"><i class="bi bi-eye"></i></a> |
                            <a class="btn btn-danger text-white "><i class="bi bi-trash"></i></a>
                        </td>
                    </tr>
                }
            </tbody>

        </table>

    </div>
</div>

Project/Project/Views/Shared/NotFound.cshtml
<div class="row ">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">Không tìm thấy</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Trang chủ</a>
    </div>

</div>

Project/Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i> Phim</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Rạp</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Nhà sản xuất</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Diễn viên</a>
                        </li>       
                    </ul>

                   <form class="form-inline my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Nhập tên phim muốn tìm...">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Project 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>